//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestGenerateID
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenerateTest
    {
        public long ID { get; set; }
        public string key1 { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string key2 { get; set; }
        public string key3 { get; set; }
    }
}
